// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalTrainer.API.Data;

#nullable disable

namespace PersonalTrainer.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714154611_AddObliquesAndFixMuscleGroups")]
    partial class AddObliquesAndFixMuscleGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("EncouragementMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusclesTargeted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.ExerciseEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTemplateId");

                    b.ToTable("ExerciseEquipment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentType = 2,
                            ExerciseTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            EquipmentType = 2,
                            ExerciseTemplateId = 2
                        },
                        new
                        {
                            Id = 3,
                            EquipmentType = 2,
                            ExerciseTemplateId = 3
                        },
                        new
                        {
                            Id = 4,
                            EquipmentType = 2,
                            ExerciseTemplateId = 4
                        },
                        new
                        {
                            Id = 5,
                            EquipmentType = 6,
                            ExerciseTemplateId = 4
                        },
                        new
                        {
                            Id = 6,
                            EquipmentType = 2,
                            ExerciseTemplateId = 5
                        },
                        new
                        {
                            Id = 7,
                            EquipmentType = 6,
                            ExerciseTemplateId = 5
                        },
                        new
                        {
                            Id = 8,
                            EquipmentType = 2,
                            ExerciseTemplateId = 6
                        },
                        new
                        {
                            Id = 9,
                            EquipmentType = 6,
                            ExerciseTemplateId = 6
                        },
                        new
                        {
                            Id = 10,
                            EquipmentType = 2,
                            ExerciseTemplateId = 7
                        },
                        new
                        {
                            Id = 11,
                            EquipmentType = 6,
                            ExerciseTemplateId = 7
                        },
                        new
                        {
                            Id = 12,
                            EquipmentType = 2,
                            ExerciseTemplateId = 8
                        },
                        new
                        {
                            Id = 13,
                            EquipmentType = 2,
                            ExerciseTemplateId = 9
                        },
                        new
                        {
                            Id = 14,
                            EquipmentType = 6,
                            ExerciseTemplateId = 9
                        },
                        new
                        {
                            Id = 15,
                            EquipmentType = 2,
                            ExerciseTemplateId = 10
                        },
                        new
                        {
                            Id = 16,
                            EquipmentType = 2,
                            ExerciseTemplateId = 11
                        },
                        new
                        {
                            Id = 17,
                            EquipmentType = 2,
                            ExerciseTemplateId = 12
                        },
                        new
                        {
                            Id = 18,
                            EquipmentType = 2,
                            ExerciseTemplateId = 13
                        },
                        new
                        {
                            Id = 19,
                            EquipmentType = 6,
                            ExerciseTemplateId = 13
                        },
                        new
                        {
                            Id = 20,
                            EquipmentType = 2,
                            ExerciseTemplateId = 14
                        },
                        new
                        {
                            Id = 21,
                            EquipmentType = 2,
                            ExerciseTemplateId = 15
                        },
                        new
                        {
                            Id = 22,
                            EquipmentType = 2,
                            ExerciseTemplateId = 16
                        },
                        new
                        {
                            Id = 23,
                            EquipmentType = 2,
                            ExerciseTemplateId = 17
                        },
                        new
                        {
                            Id = 24,
                            EquipmentType = 2,
                            ExerciseTemplateId = 18
                        },
                        new
                        {
                            Id = 25,
                            EquipmentType = 2,
                            ExerciseTemplateId = 19
                        },
                        new
                        {
                            Id = 26,
                            EquipmentType = 2,
                            ExerciseTemplateId = 20
                        },
                        new
                        {
                            Id = 27,
                            EquipmentType = 6,
                            ExerciseTemplateId = 20
                        },
                        new
                        {
                            Id = 28,
                            EquipmentType = 0,
                            ExerciseTemplateId = 21
                        },
                        new
                        {
                            Id = 29,
                            EquipmentType = 0,
                            ExerciseTemplateId = 22
                        },
                        new
                        {
                            Id = 30,
                            EquipmentType = 0,
                            ExerciseTemplateId = 23
                        },
                        new
                        {
                            Id = 31,
                            EquipmentType = 0,
                            ExerciseTemplateId = 24
                        },
                        new
                        {
                            Id = 32,
                            EquipmentType = 0,
                            ExerciseTemplateId = 25
                        },
                        new
                        {
                            Id = 33,
                            EquipmentType = 0,
                            ExerciseTemplateId = 26
                        },
                        new
                        {
                            Id = 34,
                            EquipmentType = 6,
                            ExerciseTemplateId = 26
                        },
                        new
                        {
                            Id = 35,
                            EquipmentType = 0,
                            ExerciseTemplateId = 27
                        },
                        new
                        {
                            Id = 36,
                            EquipmentType = 6,
                            ExerciseTemplateId = 27
                        },
                        new
                        {
                            Id = 37,
                            EquipmentType = 0,
                            ExerciseTemplateId = 28
                        },
                        new
                        {
                            Id = 38,
                            EquipmentType = 0,
                            ExerciseTemplateId = 29
                        },
                        new
                        {
                            Id = 39,
                            EquipmentType = 0,
                            ExerciseTemplateId = 30
                        },
                        new
                        {
                            Id = 40,
                            EquipmentType = 0,
                            ExerciseTemplateId = 31
                        },
                        new
                        {
                            Id = 41,
                            EquipmentType = 4,
                            ExerciseTemplateId = 32
                        },
                        new
                        {
                            Id = 42,
                            EquipmentType = 4,
                            ExerciseTemplateId = 33
                        },
                        new
                        {
                            Id = 43,
                            EquipmentType = 4,
                            ExerciseTemplateId = 34
                        },
                        new
                        {
                            Id = 44,
                            EquipmentType = 6,
                            ExerciseTemplateId = 34
                        },
                        new
                        {
                            Id = 45,
                            EquipmentType = 4,
                            ExerciseTemplateId = 35
                        },
                        new
                        {
                            Id = 46,
                            EquipmentType = 3,
                            ExerciseTemplateId = 36
                        },
                        new
                        {
                            Id = 47,
                            EquipmentType = 3,
                            ExerciseTemplateId = 37
                        },
                        new
                        {
                            Id = 48,
                            EquipmentType = 3,
                            ExerciseTemplateId = 38
                        },
                        new
                        {
                            Id = 49,
                            EquipmentType = 3,
                            ExerciseTemplateId = 39
                        },
                        new
                        {
                            Id = 50,
                            EquipmentType = 1,
                            ExerciseTemplateId = 40
                        },
                        new
                        {
                            Id = 51,
                            EquipmentType = 1,
                            ExerciseTemplateId = 41
                        },
                        new
                        {
                            Id = 52,
                            EquipmentType = 1,
                            ExerciseTemplateId = 42
                        },
                        new
                        {
                            Id = 53,
                            EquipmentType = 1,
                            ExerciseTemplateId = 43
                        },
                        new
                        {
                            Id = 54,
                            EquipmentType = 1,
                            ExerciseTemplateId = 44
                        },
                        new
                        {
                            Id = 55,
                            EquipmentType = 6,
                            ExerciseTemplateId = 45
                        },
                        new
                        {
                            Id = 56,
                            EquipmentType = 6,
                            ExerciseTemplateId = 46
                        },
                        new
                        {
                            Id = 57,
                            EquipmentType = 6,
                            ExerciseTemplateId = 47
                        },
                        new
                        {
                            Id = 58,
                            EquipmentType = 6,
                            ExerciseTemplateId = 48
                        },
                        new
                        {
                            Id = 59,
                            EquipmentType = 6,
                            ExerciseTemplateId = 49
                        },
                        new
                        {
                            Id = 60,
                            EquipmentType = 6,
                            ExerciseTemplateId = 50
                        },
                        new
                        {
                            Id = 61,
                            EquipmentType = 5,
                            ExerciseTemplateId = 51
                        },
                        new
                        {
                            Id = 62,
                            EquipmentType = 5,
                            ExerciseTemplateId = 52
                        },
                        new
                        {
                            Id = 63,
                            EquipmentType = 5,
                            ExerciseTemplateId = 53
                        },
                        new
                        {
                            Id = 64,
                            EquipmentType = 5,
                            ExerciseTemplateId = 54
                        });
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTemplateId");

                    b.ToTable("ExerciseMuscleGroups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseTemplateId = 1,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 2,
                            ExerciseTemplateId = 1,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseTemplateId = 1,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 4,
                            ExerciseTemplateId = 2,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 5,
                            ExerciseTemplateId = 2,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 6,
                            ExerciseTemplateId = 3,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 7,
                            ExerciseTemplateId = 3,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 8,
                            ExerciseTemplateId = 4,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 9,
                            ExerciseTemplateId = 4,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 10,
                            ExerciseTemplateId = 5,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 11,
                            ExerciseTemplateId = 6,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 12,
                            ExerciseTemplateId = 7,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 13,
                            ExerciseTemplateId = 8,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 14,
                            ExerciseTemplateId = 8,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 15,
                            ExerciseTemplateId = 9,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 16,
                            ExerciseTemplateId = 10,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 17,
                            ExerciseTemplateId = 10,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 18,
                            ExerciseTemplateId = 10,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 19,
                            ExerciseTemplateId = 11,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 20,
                            ExerciseTemplateId = 11,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 21,
                            ExerciseTemplateId = 11,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 22,
                            ExerciseTemplateId = 12,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 23,
                            ExerciseTemplateId = 12,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 24,
                            ExerciseTemplateId = 12,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 25,
                            ExerciseTemplateId = 13,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 26,
                            ExerciseTemplateId = 13,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 27,
                            ExerciseTemplateId = 14,
                            MuscleGroup = 10
                        },
                        new
                        {
                            Id = 28,
                            ExerciseTemplateId = 15,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 29,
                            ExerciseTemplateId = 15,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 30,
                            ExerciseTemplateId = 16,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 31,
                            ExerciseTemplateId = 17,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 32,
                            ExerciseTemplateId = 18,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 33,
                            ExerciseTemplateId = 19,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 34,
                            ExerciseTemplateId = 19,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 35,
                            ExerciseTemplateId = 20,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 36,
                            ExerciseTemplateId = 20,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 37,
                            ExerciseTemplateId = 21,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 38,
                            ExerciseTemplateId = 21,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 39,
                            ExerciseTemplateId = 22,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 40,
                            ExerciseTemplateId = 23,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 41,
                            ExerciseTemplateId = 24,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 42,
                            ExerciseTemplateId = 25,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 43,
                            ExerciseTemplateId = 25,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 44,
                            ExerciseTemplateId = 25,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 45,
                            ExerciseTemplateId = 26,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 46,
                            ExerciseTemplateId = 26,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 47,
                            ExerciseTemplateId = 26,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 48,
                            ExerciseTemplateId = 27,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 49,
                            ExerciseTemplateId = 27,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 50,
                            ExerciseTemplateId = 28,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 51,
                            ExerciseTemplateId = 28,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 52,
                            ExerciseTemplateId = 28,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 53,
                            ExerciseTemplateId = 29,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 54,
                            ExerciseTemplateId = 29,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 55,
                            ExerciseTemplateId = 30,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 56,
                            ExerciseTemplateId = 30,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 57,
                            ExerciseTemplateId = 30,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 58,
                            ExerciseTemplateId = 31,
                            MuscleGroup = 10
                        },
                        new
                        {
                            Id = 59,
                            ExerciseTemplateId = 32,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 60,
                            ExerciseTemplateId = 32,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 61,
                            ExerciseTemplateId = 32,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 62,
                            ExerciseTemplateId = 33,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 63,
                            ExerciseTemplateId = 33,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 64,
                            ExerciseTemplateId = 34,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 65,
                            ExerciseTemplateId = 34,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 66,
                            ExerciseTemplateId = 34,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 67,
                            ExerciseTemplateId = 35,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 68,
                            ExerciseTemplateId = 35,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 69,
                            ExerciseTemplateId = 36,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 70,
                            ExerciseTemplateId = 36,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 71,
                            ExerciseTemplateId = 36,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 72,
                            ExerciseTemplateId = 37,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 73,
                            ExerciseTemplateId = 37,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 74,
                            ExerciseTemplateId = 37,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 75,
                            ExerciseTemplateId = 38,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 76,
                            ExerciseTemplateId = 38,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 77,
                            ExerciseTemplateId = 39,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 78,
                            ExerciseTemplateId = 39,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 79,
                            ExerciseTemplateId = 40,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 80,
                            ExerciseTemplateId = 40,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 81,
                            ExerciseTemplateId = 41,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 82,
                            ExerciseTemplateId = 41,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 83,
                            ExerciseTemplateId = 42,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 84,
                            ExerciseTemplateId = 42,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 85,
                            ExerciseTemplateId = 43,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 86,
                            ExerciseTemplateId = 44,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 87,
                            ExerciseTemplateId = 44,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 88,
                            ExerciseTemplateId = 45,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 89,
                            ExerciseTemplateId = 46,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 90,
                            ExerciseTemplateId = 46,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 91,
                            ExerciseTemplateId = 47,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 92,
                            ExerciseTemplateId = 47,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 93,
                            ExerciseTemplateId = 48,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 94,
                            ExerciseTemplateId = 48,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 95,
                            ExerciseTemplateId = 49,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 96,
                            ExerciseTemplateId = 49,
                            MuscleGroup = 9
                        },
                        new
                        {
                            Id = 97,
                            ExerciseTemplateId = 50,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 98,
                            ExerciseTemplateId = 50,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 99,
                            ExerciseTemplateId = 51,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 100,
                            ExerciseTemplateId = 52,
                            MuscleGroup = 7
                        },
                        new
                        {
                            Id = 101,
                            ExerciseTemplateId = 52,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 102,
                            ExerciseTemplateId = 52,
                            MuscleGroup = 10
                        },
                        new
                        {
                            Id = 103,
                            ExerciseTemplateId = 53,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 104,
                            ExerciseTemplateId = 53,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 105,
                            ExerciseTemplateId = 54,
                            MuscleGroup = 12
                        },
                        new
                        {
                            Id = 106,
                            ExerciseTemplateId = 15,
                            MuscleGroup = 8
                        },
                        new
                        {
                            Id = 107,
                            ExerciseTemplateId = 6,
                            MuscleGroup = 11
                        },
                        new
                        {
                            Id = 108,
                            ExerciseTemplateId = 9,
                            MuscleGroup = 11
                        });
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.ExerciseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraindications")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("MaxReps")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSets")
                        .HasColumnType("int");

                    b.Property<int>("MinDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("MinReps")
                        .HasColumnType("int");

                    b.Property<int?>("MinSets")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contraindications = "wrist injury, shoulder injury",
                            Instructions = "Start in a plank position with hands shoulder-width apart. Lower your chest to the floor keeping your core tight, then push back up.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 5,
                            MinSets = 2,
                            Name = "Push Ups"
                        },
                        new
                        {
                            Id = 2,
                            Contraindications = "wrist injury, elbow injury",
                            Instructions = "Place hands close together forming a diamond shape. Lower chest toward hands keeping elbows tucked in.",
                            IsActive = true,
                            MaxDurationSeconds = 50,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 5,
                            MinSets = 2,
                            Name = "Diamond Push Ups"
                        },
                        new
                        {
                            Id = 3,
                            Contraindications = "shoulder injury",
                            Instructions = "Start in a downward dog position. Bend elbows and lower your head toward the floor, then push back up.",
                            IsActive = true,
                            MaxDurationSeconds = 50,
                            MaxReps = 15,
                            MaxSets = 3,
                            MinDurationSeconds = 20,
                            MinReps = 5,
                            MinSets = 2,
                            Name = "Pike Push Ups"
                        },
                        new
                        {
                            Id = 4,
                            Contraindications = "lower back pain",
                            Instructions = "Hold a straight line from head to heels on your forearms and toes. Engage your core throughout.",
                            IsActive = true,
                            MaxDurationSeconds = 90,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinSets = 2,
                            Name = "Plank Hold"
                        },
                        new
                        {
                            Id = 5,
                            Contraindications = "neck injury, lower back pain",
                            Instructions = "Lie on your back with knees bent. Lift your shoulders off the floor engaging your core, then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 30,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Crunches"
                        },
                        new
                        {
                            Id = 6,
                            Contraindications = "neck injury, lower back pain",
                            Instructions = "Lie on your back, hands behind head. Bring opposite elbow to knee in a cycling motion.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 30,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Bicycle Crunches"
                        },
                        new
                        {
                            Id = 7,
                            Contraindications = "lower back pain, hip flexor injury",
                            Instructions = "Lie flat on your back. Keep legs straight and raise them to 90 degrees then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Leg Raises"
                        },
                        new
                        {
                            Id = 8,
                            Contraindications = "wrist injury, shoulder injury",
                            Instructions = "Start in a plank position. Alternate driving knees toward chest in a running motion.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinSets = 2,
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = 9,
                            Contraindications = "lower back pain",
                            Instructions = "Sit with knees bent and feet off the floor. Rotate your torso side to side.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 30,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Russian Twists"
                        },
                        new
                        {
                            Id = 10,
                            Contraindications = "bad knees, knee injury",
                            Instructions = "Stand with feet shoulder-width apart. Push hips back and bend knees until thighs are parallel to floor. Push through heels to stand.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 25,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Squats"
                        },
                        new
                        {
                            Id = 11,
                            Contraindications = "bad knees, knee injury, ankle injury",
                            Instructions = "Perform a squat then explode upward jumping off the floor. Land softly and go straight into the next rep.",
                            IsActive = true,
                            MaxDurationSeconds = 50,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Jump Squats"
                        },
                        new
                        {
                            Id = 12,
                            Contraindications = "bad knees, knee injury",
                            Instructions = "Step forward with one leg and lower your hips until both knees are at 90 degrees. Push back to start and alternate legs.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = 13,
                            Contraindications = "lower back pain",
                            Instructions = "Lie on your back with knees bent. Drive hips upward squeezing glutes at the top, then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 25,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Glute Bridges"
                        },
                        new
                        {
                            Id = 14,
                            Contraindications = "ankle injury",
                            Instructions = "Stand with feet hip-width apart. Rise onto the balls of your feet, hold briefly, then lower.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 30,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Calf Raises"
                        },
                        new
                        {
                            Id = 15,
                            Contraindications = "bad knees, knee injury",
                            Instructions = "Slide your back down a wall until thighs are parallel to the floor. Hold the position.",
                            IsActive = true,
                            MaxDurationSeconds = 90,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinSets = 2,
                            Name = "Wall Sit"
                        },
                        new
                        {
                            Id = 16,
                            Contraindications = "bad knees, wrist injury, shoulder injury",
                            Instructions = "From standing, drop to a push up position, perform a push up, jump feet forward, then explode upward with arms overhead.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 5,
                            MinSets = 2,
                            Name = "Burpees"
                        },
                        new
                        {
                            Id = 17,
                            Contraindications = "knee injury, ankle injury",
                            Instructions = "Run in place driving knees as high as possible. Pump arms in rhythm.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinSets = 2,
                            Name = "High Knees"
                        },
                        new
                        {
                            Id = 18,
                            Contraindications = "ankle injury, shoulder injury",
                            Instructions = "Jump feet wide while raising arms overhead, then jump back together.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinSets = 2,
                            Name = "Jumping Jacks"
                        },
                        new
                        {
                            Id = 19,
                            Contraindications = "wrist injury, shoulder injury",
                            Instructions = "On hands and feet with knees hovering just off the floor. Move forward alternating opposite hand and foot.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxSets = 3,
                            MinDurationSeconds = 20,
                            MinSets = 2,
                            Name = "Bear Crawl"
                        },
                        new
                        {
                            Id = 20,
                            Contraindications = "lower back pain, hamstring injury",
                            Instructions = "Stand and fold forward. Walk hands out to a plank, then walk feet to hands and stand.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 3,
                            MinDurationSeconds = 20,
                            MinReps = 5,
                            MinSets = 2,
                            Name = "Inchworm"
                        },
                        new
                        {
                            Id = 21,
                            Contraindications = "shoulder injury",
                            Instructions = "Hold dumbbells at shoulder height. Press overhead until arms are extended, then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 22,
                            Contraindications = "elbow injury",
                            Instructions = "Hold dumbbells with palms facing up. Curl toward shoulders keeping elbows tucked, then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Bicep Curl"
                        },
                        new
                        {
                            Id = 23,
                            Contraindications = "elbow injury, shoulder injury",
                            Instructions = "Hold one dumbbell overhead with both hands. Lower behind your head bending at elbows, then extend back up.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Tricep Extension"
                        },
                        new
                        {
                            Id = 24,
                            Contraindications = "shoulder injury",
                            Instructions = "Hold dumbbells at sides. Raise arms out to the side to shoulder height then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Lateral Raises"
                        },
                        new
                        {
                            Id = 25,
                            Contraindications = "lower back pain",
                            Instructions = "Hinge forward at the hips. Pull dumbbells toward your ribcage squeezing shoulder blades, then lower.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Bent Over Row"
                        },
                        new
                        {
                            Id = 26,
                            Contraindications = "shoulder injury",
                            Instructions = "Lie on your back with dumbbells at chest height. Press upward until arms are extended then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Chest Press"
                        },
                        new
                        {
                            Id = 27,
                            Contraindications = "shoulder injury",
                            Instructions = "Lie on your back holding dumbbells above chest. Open arms wide in an arc then bring back together.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 12,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Chest Fly"
                        },
                        new
                        {
                            Id = 28,
                            Contraindications = "bad knees, knee injury",
                            Instructions = "Hold dumbbells at sides or shoulders. Perform a squat keeping chest up and knees tracking over toes.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Squat"
                        },
                        new
                        {
                            Id = 29,
                            Contraindications = "bad knees, knee injury",
                            Instructions = "Hold dumbbells at sides. Step forward and lower until both knees are at 90 degrees then return.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 16,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Lunges"
                        },
                        new
                        {
                            Id = 30,
                            Contraindications = "lower back pain, hamstring injury",
                            Instructions = "Hold dumbbells in front. Hinge at hips keeping back straight lowering weights along legs, then drive hips forward to stand.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 30,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dumbbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = 31,
                            Contraindications = "ankle injury",
                            Instructions = "Hold dumbbells at sides. Rise onto balls of feet hold briefly then lower.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 25,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Dumbbell Calf Raises"
                        },
                        new
                        {
                            Id = 32,
                            Contraindications = "lower back pain, shoulder injury",
                            Instructions = "Hinge at hips holding kettlebell. Drive hips forward explosively swinging the bell to chest height, then hinge back.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 25,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Kettlebell Swing"
                        },
                        new
                        {
                            Id = 33,
                            Contraindications = "bad knees, knee injury",
                            Instructions = "Hold kettlebell at chest with both hands. Squat deep keeping chest up and elbows inside knees.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Kettlebell Goblet Squat"
                        },
                        new
                        {
                            Id = 34,
                            Contraindications = "shoulder injury, wrist injury",
                            Instructions = "Lie holding kettlebell overhead. Follow a sequence to stand while keeping the bell pressed overhead, then reverse.",
                            IsActive = true,
                            MaxDurationSeconds = 90,
                            MaxReps = 6,
                            MaxSets = 3,
                            MinDurationSeconds = 30,
                            MinReps = 2,
                            MinSets = 2,
                            Name = "Kettlebell Turkish Get Up"
                        },
                        new
                        {
                            Id = 35,
                            Contraindications = "shoulder injury, wrist injury",
                            Instructions = "Clean kettlebell to shoulder then press overhead. Lower with control and repeat.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 12,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 6,
                            MinSets = 2,
                            Name = "Kettlebell Clean and Press"
                        },
                        new
                        {
                            Id = 36,
                            Contraindications = "shoulder injury, elbow injury",
                            Instructions = "Hang from bar with overhand grip. Pull yourself up until chin clears the bar then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 2,
                            MinSets = 2,
                            Name = "Pull Ups"
                        },
                        new
                        {
                            Id = 37,
                            Contraindications = "shoulder injury, elbow injury",
                            Instructions = "Hang from bar with underhand grip. Pull yourself up until chin clears the bar then lower slowly.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 2,
                            MinSets = 2,
                            Name = "Chin Ups"
                        },
                        new
                        {
                            Id = 38,
                            Contraindications = "shoulder injury",
                            Instructions = "Hang from bar with both hands. Relax your shoulders and hang for the prescribed time.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxSets = 4,
                            MinDurationSeconds = 15,
                            MinSets = 2,
                            Name = "Dead Hang"
                        },
                        new
                        {
                            Id = 39,
                            Contraindications = "shoulder injury, hip flexor injury",
                            Instructions = "Hang from bar. Drive knees toward chest engaging core then lower with control.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Hanging Knee Raises"
                        },
                        new
                        {
                            Id = 40,
                            Contraindications = "shoulder injury",
                            Instructions = "Hold band at chest width with both hands. Pull apart horizontally squeezing shoulder blades, then return.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 25,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Resistance Band Pull Apart"
                        },
                        new
                        {
                            Id = 41,
                            Contraindications = "bad knees, knee injury",
                            Instructions = "Stand on band holding ends at shoulders. Perform a squat keeping tension throughout.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 25,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Resistance Band Squat"
                        },
                        new
                        {
                            Id = 42,
                            Contraindications = "lower back pain",
                            Instructions = "Anchor band at waist height. Hold ends and pull toward your torso squeezing shoulder blades.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Resistance Band Row"
                        },
                        new
                        {
                            Id = 43,
                            Contraindications = "elbow injury",
                            Instructions = "Stand on band with palms facing up. Curl hands toward shoulders keeping elbows tucked.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Resistance Band Bicep Curl"
                        },
                        new
                        {
                            Id = 44,
                            Contraindications = "hip injury, knee injury",
                            Instructions = "Loop band around ankles on all fours. Kick one leg back squeezing glute at the top, then alternate.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 10,
                            MinSets = 2,
                            Name = "Resistance Band Glute Kickback"
                        },
                        new
                        {
                            Id = 45,
                            Contraindications = "knee injury",
                            Instructions = "Kneel and sit back on heels. Extend arms forward resting forehead on mat. Breathe deeply.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxSets = 3,
                            MinDurationSeconds = 20,
                            MinSets = 1,
                            Name = "Child's Pose"
                        },
                        new
                        {
                            Id = 46,
                            Contraindications = "lower back pain",
                            Instructions = "On all fours alternate arching your back toward the ceiling then dropping it toward the floor.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 3,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Cat Cow Stretch"
                        },
                        new
                        {
                            Id = 47,
                            Contraindications = "lower back pain",
                            Instructions = "Lie face down with arms extended. Simultaneously lift arms and legs off the mat, hold briefly then lower.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 15,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Superman Hold"
                        },
                        new
                        {
                            Id = 48,
                            Contraindications = "lower back pain, wrist injury",
                            Instructions = "Lie face down with hands under shoulders. Press up lifting chest while keeping hips on mat.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxSets = 3,
                            MinDurationSeconds = 20,
                            MinSets = 2,
                            Name = "Cobra Stretch"
                        },
                        new
                        {
                            Id = 49,
                            Contraindications = "knee injury, hip injury",
                            Instructions = "Kneel on one knee with the other foot forward. Drive hips forward feeling the stretch in the front of the back hip.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxSets = 3,
                            MinDurationSeconds = 20,
                            MinSets = 2,
                            Name = "Hip Flexor Stretch"
                        },
                        new
                        {
                            Id = 50,
                            Contraindications = "lower back pain",
                            Instructions = "Lie on back with arms up and knees at 90 degrees. Lower opposite arm and leg toward floor while keeping lower back pressed down.",
                            IsActive = true,
                            MaxDurationSeconds = 60,
                            MaxReps = 20,
                            MaxSets = 4,
                            MinDurationSeconds = 20,
                            MinReps = 8,
                            MinSets = 2,
                            Name = "Dead Bug"
                        },
                        new
                        {
                            Id = 51,
                            Contraindications = "bad knees, ankle injury",
                            Instructions = "Run at a comfortable pace on the treadmill. Maintain upright posture and land midfoot.",
                            IsActive = true,
                            MaxDurationSeconds = 300,
                            MaxSets = 3,
                            MinDurationSeconds = 60,
                            MinSets = 1,
                            Name = "Treadmill Run"
                        },
                        new
                        {
                            Id = 52,
                            Contraindications = "knee injury",
                            Instructions = "Cycle at a steady pace maintaining consistent cadence. Adjust resistance to appropriate level.",
                            IsActive = true,
                            MaxDurationSeconds = 300,
                            MaxSets = 3,
                            MinDurationSeconds = 60,
                            MinSets = 1,
                            Name = "Stationary Bike"
                        },
                        new
                        {
                            Id = 53,
                            Contraindications = "lower back pain, shoulder injury",
                            Instructions = "Drive with legs first then lean back and pull handle to lower chest. Return in reverse order.",
                            IsActive = true,
                            MaxDurationSeconds = 300,
                            MaxSets = 3,
                            MinDurationSeconds = 60,
                            MinSets = 1,
                            Name = "Rowing Machine"
                        },
                        new
                        {
                            Id = 54,
                            Contraindications = "ankle injury",
                            Instructions = "Use the elliptical at a steady pace pushing and pulling the handles while maintaining upright posture.",
                            IsActive = true,
                            MaxDurationSeconds = 300,
                            MaxSets = 3,
                            MinDurationSeconds = 60,
                            MinSets = 1,
                            Name = "Elliptical"
                        });
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.UserWorkoutProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("int");

                    b.Property<int>("FocusArea")
                        .HasColumnType("int");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<string>("HealthLimitations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserWorkoutProfiles");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompletionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CooldownCue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivationalIntro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserWorkoutProfileId")
                        .HasColumnType("int");

                    b.Property<string>("WarmupCue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserWorkoutProfileId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalTrainer.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.Exercise", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.ExerciseEquipment", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.ExerciseTemplate", "ExerciseTemplate")
                        .WithMany("Equipment")
                        .HasForeignKey("ExerciseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseTemplate");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.ExerciseTemplate", "ExerciseTemplate")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("ExerciseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseTemplate");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.RefreshToken", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.UserWorkoutProfile", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.WorkoutPlan", b =>
                {
                    b.HasOne("PersonalTrainer.API.Models.UserWorkoutProfile", "UserWorkoutProfile")
                        .WithMany()
                        .HasForeignKey("UserWorkoutProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserWorkoutProfile");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.ExerciseTemplate", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("PersonalTrainer.API.Models.WorkoutPlan", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
